### PR TITLE
Swift 3 udpates

### PR DESCRIPTION
**Pull request by mborkow**
I've been using your library and when I converted to Swift 3 I had to update this as well. The tests are currently passing (and the functionality I am using is working nicely).

### CODE REVIEW

**Comment by peheje** [comment]
Hey!
Thank you very much. Sorry for the late response!

I'll merge these fixes in whenever Swift 3.0 gets released.

**Comment by mborkow** [comment]
Your library saved me a ton of time and when I had to update to Swift 3 I
figured the least I could do was give back!

**Comment by peheje** [comment]
Very generous 😀 glad to hear I'm helping a tiny bit in the world.

**Comment by peheje** [comment]
As Swift 3 is released. I have merged your changes into it! Nice! Seems like you also fixed some bugs with serializing arrays, all tests pass! 👍

**Pull request merged**
